language: node_js
node_js:
  - "12"
  - "10"
  - "8"
cache:
  yarn: true
before_install:
  - npm install --global yarn nyc
script:
  - yarn lint
  - yarn test-coverage
after_script:
  - npm install --global codecov coveralls
  - cat ./coverage/lcov.info | coveralls
  - cat ./coverage/lcov.info | codecov
