language: node_js
node_js:
  - "8"
  - "10"
  - "12"
cache:
  yarn: true
before_install:
  - npm install --global yarn nyc codecov coveralls
script:
  - yarn lint
  - nyc yarn test
after_script:
  - nyc report --reporter=text-lcov | coveralls
  - nyc report --reporter=text-lcov > coverage.lcov && codecov
